apiVersion: v1 
kind: Service 
metadata: 
  name: vpn-gateway-service
  labels:
    app: vpn-gateway
spec: 
  selector: 
    app: vpn-gateway
  ports:
    - port: 29170
      targetPort: 29170
      protocol: TCP
  type: NodePort
